### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by aescolastico** [jsternberg/ansible-agent#1]
Hello @jsternberg 
This project is very unique and interesting. Is there any documentation on how to setup a server client configuration or how to push playbooks to devices with the daemon installed?

**Comment by jsternberg** [comment]
Hi, I just noticed that this repository had some attention. I can't really remember how far I got with this project and I haven't used Ansible in 7-ish years so this repository is probably very out of date and probably doesn't work. I believe this was an experiment of mine and it wasn't used in a production capacity, but I can't remember if that was just because it wasn't finished, the need for it disappeared, or if it was just never done for some other reason.

I'm going to add a commit explaining this and then archive it just in case someone else finds it useful as a base for something else, but I don't really remember anything beyond the README a past version of me left behind.

I do remember that the file in connection plugins was intended to be used by ansible as a custom transport. It was intended to be configured with a client certificate as a substitute for an ssh private key (in contrast to how a web server is set up where the certificate verifies the server and not the client).
